name: Build and Run Dockerfile

on:
  push:
    branches: [main]  # main 브랜치에 푸시될 때 작동
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions에서 제공하는 리눅스 러너 사용

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-app-image .

      - name: Run Docker container
        run: |
          docker run -d -p 8080:3000 --name my-app-container my-app-image

